/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 cub.gltf --shadows 
*/

/* eslint-disable */

import React , { useEffect, useRef } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, OrthographicCamera } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import { cubCubePosition } from '../../constants'
export default function Cup(props) {
  const { scene } = useGLTF('/assets/model/cub.gltf')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const meshGroupRef = useRef(null);

  useEffect(() => {
    const allMesh = meshGroupRef.current.children
    .slice(3)
    .flatMap((parent) =>
      parent.children ? Array.from(parent.children) : [],
    );

    const meshData = allMesh.map((mesh) => ({
      position: mesh.position.clone(), 
    }));

  },[])

  return (
    <group {...props} dispose={null}>
      <group scale={0.01} ref={meshGroupRef}>
        <directionalLight intensity={1} decay={2} rotation={[0, 0.48, 0]} target={nodes.Directional_Light.target}>
          <primitive object={nodes.Directional_Light.target} position={[0, 0, -1]} />
        </directionalLight>
        <OrthographicCamera makeDefault={false} far={100000} near={0} position={[-215.812, 127.945, 1093.227]} rotation={[-0.113, -0.14, -0.016]} />
        <group position={[-1.388, 30.674, -3.706]}>
          <mesh castShadow receiveShadow geometry={nodes.ears_1.geometry} material={nodes.ears_1.material} position={[3.619, 4.347, 0]} />
          <mesh castShadow receiveShadow geometry={nodes.ears_2.geometry} material={nodes.ears_2.material} position={[10.634, -4.476, 0]} />
          <mesh castShadow receiveShadow geometry={nodes.ears_3.geometry} material={nodes.ears_3.material} position={[-10.634, 4.476, 0]} />
          <mesh castShadow receiveShadow geometry={nodes.ears_4.geometry} material={nodes.ears_4.material} position={[-5.623, -4.476, 0]} />
        </group>
        <group position={[0.047, 21.998, 5.701]}>
          <mesh castShadow receiveShadow geometry={nodes.cube_344.geometry} material={nodes.cube_344.material} position={[5.312, -3.817, -15.926]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_345.geometry} material={nodes.cube_345.material} position={[-5.689, 4.551, -5.33]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_346.geometry} material={nodes.cube_346.material} position={[7.612, 12.252, -7.526]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_347.geometry} material={nodes.cube_347.material} position={[9.033, 2.552, -17.464]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_348.geometry} material={nodes.cube_348.material} position={[-0.092, 2.552, -17.464]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_349.geometry} material={nodes.cube_349.material} position={[-9.217, 2.552, -17.464]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_350.geometry} material={nodes.cube_350.material} position={[-1.517, 12.252, -7.526]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_351.geometry} material={nodes.cube_351.material} position={[5.124, 6.857, -4.183]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_352.geometry} material={nodes.cube_352.material} position={[-4.001, 6.857, -4.183]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_353.geometry} material={nodes.cube_353.material} position={[-13.126, 6.857, -4.183]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_354.geometry} material={nodes.cube_354.material} position={[7.612, 3.122, -7.526]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_355.geometry} material={nodes.cube_355.material} position={[-1.517, 3.122, -7.526]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_356.geometry} material={nodes.cube_356.material} position={[12.063, -7.389, 1.937]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_357.geometry} material={nodes.cube_357.material} position={[2.938, -7.389, 1.937]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_358.geometry} material={nodes.cube_358.material} position={[-6.187, -7.389, 1.937]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_359.geometry} material={nodes.cube_359.material} position={[17.978, -11.084, 17.464]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_360.geometry} material={nodes.cube_360.material} position={[9.098, -11.084, 17.464]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_361.geometry} material={nodes.cube_361.material} position={[1.238, -11.084, 17.464]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_362.geometry} material={nodes.cube_362.material} position={[-5.974, -11.084, 17.464]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_363.geometry} material={nodes.cube_363.material} position={[-14.685, -11.084, 17.464]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_364.geometry} material={nodes.cube_364.material} position={[-12.435, 4.435, 7.893]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_365.geometry} material={nodes.cube_365.material} position={[9.911, 4.435, 7.893]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_366.geometry} material={nodes.cube_366.material} position={[-6.044, 4.435, 7.893]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_367.geometry} material={nodes.cube_367.material} position={[-21.473, 4.435, 7.893]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_368.geometry} material={nodes.cube_368.material} position={[1.722, 5.998, -5.566]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_369.geometry} material={nodes.cube_369.material} position={[5.312, 5.308, 7.464]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_370.geometry} material={nodes.cube_370.material} position={[21.473, 4.294, -5.33]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_371.geometry} material={nodes.cube_371.material} position={[13.671, 4.294, -5.33]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_372.geometry} material={nodes.cube_372.material} position={[3.614, 5.795, -5.33]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_373.geometry} material={nodes.cube_373.material} position={[1.722, -3.127, -5.566]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_374.geometry} material={nodes.cube_374.material} position={[1.722, -12.252, -5.566]} />
        </group>
        <group position={[0.383, 24.402, -1.037]}>
          <mesh castShadow receiveShadow geometry={nodes.cube_294.geometry} material={nodes.cube_294.material} position={[6.563, -4.696, 10.875]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_295.geometry} material={nodes.cube_295.material} position={[15.427, -4.696, 10.875]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_296.geometry} material={nodes.cube_296.material} position={[2.187, 2.828, 5.154]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_297.geometry} material={nodes.cube_297.material} position={[-14.531, 10.215, 12.222]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_298.geometry} material={nodes.cube_298.material} position={[11.483, 0.68, -6.798]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_299.geometry} material={nodes.cube_299.material} position={[-15.885, 0.68, -6.798]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_300.geometry} material={nodes.cube_300.material} position={[-6.765, 0.68, -6.798]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_301.geometry} material={nodes.cube_301.material} position={[2.358, 0.68, -6.798]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_302.geometry} material={nodes.cube_302.material} position={[-6.943, 2.828, 5.154]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_303.geometry} material={nodes.cube_303.material} position={[14.953, -2.447, -5.292]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_304.geometry} material={nodes.cube_304.material} position={[5.828, -2.447, -5.292]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_305.geometry} material={nodes.cube_305.material} position={[-3.297, -2.447, -5.292]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_306.geometry} material={nodes.cube_306.material} position={[2.085, -9.559, 14.258]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_307.geometry} material={nodes.cube_307.material} position={[-7.045, -9.559, 14.258]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_308.geometry} material={nodes.cube_308.material} position={[14.856, -6.778, 4.555]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_309.geometry} material={nodes.cube_309.material} position={[5.731, -6.778, 4.555]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_310.geometry} material={nodes.cube_310.material} position={[-3.394, -6.778, 4.555]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_311.geometry} material={nodes.cube_311.material} position={[1.573, 5.51, 7.912]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_312.geometry} material={nodes.cube_312.material} position={[-7.557, 5.51, 7.912]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_313.geometry} material={nodes.cube_313.material} position={[11.999, 1.758, -8.449]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_314.geometry} material={nodes.cube_314.material} position={[2.874, 1.758, -8.449]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_315.geometry} material={nodes.cube_315.material} position={[-6.251, 1.758, -8.449]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_316.geometry} material={nodes.cube_316.material} position={[19.201, -5.992, 8.438]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_317.geometry} material={nodes.cube_317.material} position={[6.069, 2.49, 10.875]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_318.geometry} material={nodes.cube_318.material} position={[12.015, -6.272, 8.438]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_319.geometry} material={nodes.cube_319.material} position={[16.929, 5.711, 10.875]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_320.geometry} material={nodes.cube_320.material} position={[8.33, -1.09, 15.724]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_321.geometry} material={nodes.cube_321.material} position={[-19.201, 5.627, -15.724]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_322.geometry} material={nodes.cube_322.material} position={[-10.071, 5.627, -15.724]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_323.geometry} material={nodes.cube_323.material} position={[-0.951, 5.627, -15.724]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_324.geometry} material={nodes.cube_324.material} position={[8.169, 5.627, -15.724]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_325.geometry} material={nodes.cube_325.material} position={[17.299, 5.627, -15.724]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_326.geometry} material={nodes.cube_326.material} position={[-5.404, 10.215, 12.222]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_327.geometry} material={nodes.cube_327.material} position={[3.716, 10.215, 12.222]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_328.geometry} material={nodes.cube_328.material} position={[-12.415, -2.452, -5.292]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_329.geometry} material={nodes.cube_329.material} position={[-12.512, -6.778, 4.555]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_330.geometry} material={nodes.cube_330.material} position={[-15.369, 1.758, -8.449]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_331.geometry} material={nodes.cube_331.material} position={[11.304, 2.823, 5.154]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_332.geometry} material={nodes.cube_332.material} position={[11.202, -9.559, 14.258]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_333.geometry} material={nodes.cube_333.material} position={[10.69, 5.51, 7.912]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_334.geometry} material={nodes.cube_334.material} position={[-0.788, -1.085, 15.724]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_335.geometry} material={nodes.cube_335.material} position={[-0.788, -10.215, 15.724]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_336.geometry} material={nodes.cube_336.material} position={[-5.814, 9.101, 10.115]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_337.geometry} material={nodes.cube_337.material} position={[-5.814, 9.34, -6.261]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_338.geometry} material={nodes.cube_338.material} position={[13.272, 1.636, 3.21]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_339.geometry} material={nodes.cube_339.material} position={[2.404, 1.636, 3.21]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_340.geometry} material={nodes.cube_340.material} position={[-7.46, 1.636, 3.21]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_341.geometry} material={nodes.cube_341.material} position={[-16.863, 1.636, 3.21]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_342.geometry} material={nodes.cube_342.material} position={[8.33, -10.215, 15.724]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_343.geometry} material={nodes.cube_343.material} position={[4.381, 0.215, -6.261]} />
        </group>
        <group position={[0, 23.681, 0.076]}>
          <mesh castShadow receiveShadow geometry={nodes.cube_224.geometry} material={nodes.cube_224.material} position={[15.002, -2.672, -11.108]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_225.geometry} material={nodes.cube_225.material} position={[-17.568, -7.828, 3.962]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_226.geometry} material={nodes.cube_226.material} position={[27.395, 17.71, 18.195]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_227.geometry} material={nodes.cube_227.material} position={[27.395, 17.71, 18.195]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_228.geometry} material={nodes.cube_228.material} position={[27.395, 17.71, -9.125]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_229.geometry} material={nodes.cube_229.material} position={[27.395, 17.71, -18.175]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_230.geometry} material={nodes.cube_230.material} position={[27.395, 17.71, 0.005]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_231.geometry} material={nodes.cube_231.material} position={[27.395, 17.71, 9.135]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_233.geometry} material={nodes.cube_233.material} position={[-27.515, 17.71, 18.213]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_234.geometry} material={nodes.cube_234.material} position={[-27.515, 17.71, 9.205]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_235.geometry} material={nodes.cube_235.material} position={[-27.515, 17.71, 0.095]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_236.geometry} material={nodes.cube_236.material} position={[18.205, 17.71, 27.265]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_237.geometry} material={nodes.cube_237.material} position={[9.075, 17.71, 27.265]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_238.geometry} material={nodes.cube_238.material} position={[-0.045, 17.71, 27.265]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_239.geometry} material={nodes.cube_239.material} position={[-9.165, 17.71, 27.265]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_240.geometry} material={nodes.cube_240.material} position={[-18.295, 17.71, 27.265]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_241.geometry} material={nodes.cube_241.material} position={[9.115, 17.71, -27.265]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_242.geometry} material={nodes.cube_242.material} position={[-0.005, 17.71, -27.265]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_243.geometry} material={nodes.cube_243.material} position={[-9.135, 17.71, -27.265]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_243_1.geometry} material={nodes.cube_243_1.material} position={[-18.345, 17.71, -27.265]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_244.geometry} material={nodes.cube_244.material} position={[-27.515, 17.71, -18.135]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_245.geometry} material={nodes.cube_245.material} position={[6.776, -4.798, -12.644]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_246.geometry} material={nodes.cube_246.material} position={[-17.558, -3.484, 7.908]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_247.geometry} material={nodes.cube_247.material} position={[-0.031, -0.467, -10.525]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_248.geometry} material={nodes.cube_248.material} position={[-15.926, -1.364, -10.525]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_249.geometry} material={nodes.cube_249.material} position={[18.685, -12.849, 2.015]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_250.geometry} material={nodes.cube_250.material} position={[-27.415, 17.71, 27.265]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_251.geometry} material={nodes.cube_251.material} position={[-9.135, 17.71, -27.265]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_252.geometry} material={nodes.cube_252.material} position={[-0.005, 17.71, -27.265]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_253.geometry} material={nodes.cube_253.material} position={[9.115, 17.71, -27.265]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_254.geometry} material={nodes.cube_254.material} position={[18.235, 17.71, -27.265]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_255.geometry} material={nodes.cube_255.material} position={[27.365, 17.71, -27.265]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_256.geometry} material={nodes.cube_256.material} position={[-18.295, 17.71, 27.265]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_257.geometry} material={nodes.cube_257.material} position={[-9.165, 17.71, 27.265]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_258.geometry} material={nodes.cube_258.material} position={[-0.045, 17.71, 27.265]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_259.geometry} material={nodes.cube_259.material} position={[9.075, 17.71, 27.265]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_260.geometry} material={nodes.cube_260.material} position={[27.325, 17.71, 27.265]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_261.geometry} material={nodes.cube_261.material} position={[18.205, 17.71, 27.265]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_262.geometry} material={nodes.cube_262.material} position={[-27.515, 17.71, -18.135]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_263.geometry} material={nodes.cube_263.material} position={[-18.345, 17.71, -27.265]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_265.geometry} material={nodes.cube_265.material} position={[-0.825, -9.964, -1.543]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_266.geometry} material={nodes.cube_266.material} position={[-27.515, 17.71, -27.265]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_267.geometry} material={nodes.cube_267.material} position={[-7.081, 1.105, 2.958]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_268.geometry} material={nodes.cube_268.material} position={[-6.945, -11.873, 17.023]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_269.geometry} material={nodes.cube_269.material} position={[5.861, -0.983, -0.148]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_270.geometry} material={nodes.cube_270.material} position={[27.395, 17.71, -9.125]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_271.geometry} material={nodes.cube_271.material} position={[27.395, 17.71, 9.135]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_272.geometry} material={nodes.cube_272.material} position={[9.115, 17.71, -27.265]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_273.geometry} material={nodes.cube_273.material} position={[27.365, 17.71, -27.265]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_274.geometry} material={nodes.cube_274.material} position={[0.333, 0.55, -15.088]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_275.geometry} material={nodes.cube_275.material} position={[27.395, 17.71, -18.175]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_276.geometry} material={nodes.cube_276.material} position={[-27.515, 17.71, -8.945]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_277.geometry} material={nodes.cube_277.material} position={[-27.415, 17.71, 27.265]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_278.geometry} material={nodes.cube_278.material} position={[-27.515, 17.71, -8.945]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_279.geometry} material={nodes.cube_279.material} position={[27.395, 17.71, 0.005]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_280.geometry} material={nodes.cube_280.material} position={[27.325, 17.71, 27.265]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_281.geometry} material={nodes.cube_281.material} position={[18.235, 17.71, -27.265]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_282.geometry} material={nodes.cube_282.material} position={[-0.58, -7.427, 7.281]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_283.geometry} material={nodes.cube_283.material} position={[5.004, -2.608, 8.408]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_284.geometry} material={nodes.cube_284.material} position={[8.068, -5.579, -5.966]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_285.geometry} material={nodes.cube_285.material} position={[0.333, -17.71, -15.088]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_286.geometry} material={nodes.cube_286.material} position={[0.333, -8.58, -15.088]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_287.geometry} material={nodes.cube_287.material} position={[-8.787, -8.58, -15.088]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_288.geometry} material={nodes.cube_288.material} position={[-9.129, -3.051, -6.848]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_289.geometry} material={nodes.cube_289.material} position={[-17.558, -12.609, 7.908]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_290.geometry} material={nodes.cube_290.material} position={[0.018, -3.627, -3.315]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_291.geometry} material={nodes.cube_291.material} position={[-16.489, -3.627, -3.315]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_292.geometry} material={nodes.cube_292.material} position={[18.685, -14.119, 9.42]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_293.geometry} material={nodes.cube_293.material} position={[14.756, -12.41, 15.715]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_232.geometry} material={nodes.cube_232.material} position={[-45.292, -0.687, 0.066]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_264.geometry} material={nodes.cube_264.material} position={[45.292, -0.701, -0.089]} />
        </group>
        <group position={[-0.071, 13.952, 0.006]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh castShadow receiveShadow geometry={nodes.cube_153.geometry} material={nodes.cube_153.material} position={[0.049, -27.187, -9.12]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_154.geometry} material={nodes.cube_154.material} position={[-9.039, -27.16, -9.12]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_155.geometry} material={nodes.cube_155.material} position={[18.268, 9.133, 9.12]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_156.geometry} material={nodes.cube_156.material} position={[9.139, 18.263, 9.12]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_157.geometry} material={nodes.cube_157.material} position={[0.014, 18.263, 9.12]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_158.geometry} material={nodes.cube_158.material} position={[-27.484, 18.263, 0]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_159.geometry} material={nodes.cube_159.material} position={[-18.234, 18.263, 9.12]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_160.geometry} material={nodes.cube_160.material} position={[-9.111, 18.263, 9.12]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_161.geometry} material={nodes.cube_161.material} position={[9.139, 9.133, 9.12]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_162.geometry} material={nodes.cube_162.material} position={[0.014, 9.133, 9.12]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_163.geometry} material={nodes.cube_163.material} position={[-9.111, 9.133, 9.12]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_164.geometry} material={nodes.cube_164.material} position={[-18.236, 9.133, 9.12]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_165.geometry} material={nodes.cube_165.material} position={[18.268, 0.003, 9.12]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_166.geometry} material={nodes.cube_166.material} position={[9.139, 0.003, 9.12]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_167.geometry} material={nodes.cube_167.material} position={[0.014, 0.003, 9.12]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_168.geometry} material={nodes.cube_168.material} position={[-9.111, 0.003, 9.12]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_169.geometry} material={nodes.cube_169.material} position={[-18.236, 0.003, 9.12]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_170.geometry} material={nodes.cube_170.material} position={[18.268, -9.127, 9.12]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_171.geometry} material={nodes.cube_171.material} position={[9.139, -9.127, 9.12]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_172.geometry} material={nodes.cube_172.material} position={[0.014, -9.127, 9.12]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_173.geometry} material={nodes.cube_173.material} position={[-9.111, -9.127, 9.12]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_174.geometry} material={nodes.cube_174.material} position={[-18.236, -9.127, 9.12]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_175.geometry} material={nodes.cube_175.material} position={[18.268, -18.262, 9.12]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_176.geometry} material={nodes.cube_176.material} position={[9.139, -18.262, 9.12]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_177.geometry} material={nodes.cube_177.material} position={[0.014, -18.262, 9.12]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_178.geometry} material={nodes.cube_178.material} position={[-9.111, -18.262, 9.12]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_179.geometry} material={nodes.cube_179.material} position={[-18.236, -18.262, 9.12]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_181.geometry} material={nodes.cube_181.material} position={[18.236, 27.313, -9.12]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_183.geometry} material={nodes.cube_183.material} position={[9.126, 27.313, -9.12]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_184.geometry} material={nodes.cube_184.material} position={[27.386, 27.313, -9.12]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_185.geometry} material={nodes.cube_185.material} position={[27.386, 18.233, -9.12]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_186.geometry} material={nodes.cube_186.material} position={[-18.234, 27.331, 0]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_187.geometry} material={nodes.cube_187.material} position={[-9.104, 27.331, 0.004]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_188.geometry} material={nodes.cube_188.material} position={[0.016, 27.331, 0.004]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_189.geometry} material={nodes.cube_189.material} position={[9.136, 27.331, 0.004]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_190.geometry} material={nodes.cube_190.material} position={[27.386, 27.331, 0.004]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_191.geometry} material={nodes.cube_191.material} position={[18.266, 27.331, 0.004]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_192.geometry} material={nodes.cube_192.material} position={[18.266, 18.263, 9.12]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_193.geometry} material={nodes.cube_193.material} position={[-27.394, 27.387, -9.12]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_194.geometry} material={nodes.cube_194.material} position={[-27.484, 18.34, -9.12]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_195.geometry} material={nodes.cube_195.material} position={[-27.431, 9.372, -9.12]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_196.geometry} material={nodes.cube_196.material} position={[-27.431, 0.168, -9.12]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_197.geometry} material={nodes.cube_197.material} position={[-27.429, -8.964, -9.12]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_198.geometry} material={nodes.cube_198.material} position={[-27.431, -27.304, -9.12]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_199.geometry} material={nodes.cube_199.material} position={[-27.431, -18.017, -9.12]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_200.geometry} material={nodes.cube_200.material} position={[27.386, 9.173, -9.12]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_201.geometry} material={nodes.cube_201.material} position={[27.391, 0.039, -9.12]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_202.geometry} material={nodes.cube_202.material} position={[27.391, -9.086, -9.12]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_203.geometry} material={nodes.cube_203.material} position={[27.391, -18.216, -9.12]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_204.geometry} material={nodes.cube_204.material} position={[27.453, -27.187, -9.12]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_205.geometry} material={nodes.cube_205.material} position={[27.484, 18.263, 0]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_206.geometry} material={nodes.cube_206.material} position={[-27.484, 9.128, 0]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_207.geometry} material={nodes.cube_207.material} position={[-27.484, 0.003, 0]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_208.geometry} material={nodes.cube_208.material} position={[-27.484, -9.127, 0]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_209.geometry} material={nodes.cube_209.material} position={[27.484, 9.128, 0]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_210.geometry} material={nodes.cube_210.material} position={[27.484, 0.003, 0]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_211.geometry} material={nodes.cube_211.material} position={[27.484, -9.127, 0]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_212.geometry} material={nodes.cube_212.material} position={[-27.484, -18.257, 0]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_213.geometry} material={nodes.cube_213.material} position={[-27.484, -27.387, 0]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_214.geometry} material={nodes.cube_214.material} position={[27.484, -18.257, 0]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_215.geometry} material={nodes.cube_215.material} position={[9.146, -27.187, -9.12]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_216.geometry} material={nodes.cube_216.material} position={[18.266, -27.187, -9.12]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_217.geometry} material={nodes.cube_217.material} position={[27.484, -27.387, 0]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_218.geometry} material={nodes.cube_218.material} position={[18.266, -27.35, 0]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_219.geometry} material={nodes.cube_219.material} position={[9.139, -27.31, 0]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_220.geometry} material={nodes.cube_220.material} position={[0.014, -27.31, 0]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_221.geometry} material={nodes.cube_221.material} position={[-9.111, -27.31, 0]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_222.geometry} material={nodes.cube_222.material} position={[-18.236, -27.31, 0]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_223.geometry} material={nodes.cube_223.material} position={[-18.237, -27.264, -9.12]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_180.geometry} material={nodes.cube_180.material} position={[-27.394, 27.253, 0]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_182.geometry} material={nodes.cube_182.material} position={[0.036, 27.313, -9.12]} />
        </group>
        <group position={[-0.032, -4.575, 0]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh castShadow receiveShadow geometry={nodes.cube_82.geometry} material={nodes.cube_82.material} position={[36.403, 0.045, -36.69]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_83.geometry} material={nodes.cube_83.material} position={[-0.026, -13.386, 36.816]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_84.geometry} material={nodes.cube_84.material} position={[27.441, 9.139, -36.814]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_85.geometry} material={nodes.cube_85.material} position={[9.099, 27.366, -36.816]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_86.geometry} material={nodes.cube_86.material} position={[-0.026, 27.366, -36.816]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_87.geometry} material={nodes.cube_87.material} position={[-27.393, 27.366, -36.816]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_88.geometry} material={nodes.cube_88.material} position={[-18.273, 27.366, -36.816]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_89.geometry} material={nodes.cube_89.material} position={[-9.151, 27.366, -36.816]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_90.geometry} material={nodes.cube_90.material} position={[-18.264, 27.329, -27.654]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_91.geometry} material={nodes.cube_91.material} position={[-0.026, 9.139, 18.706]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_92.geometry} material={nodes.cube_92.material} position={[-9.153, 27.329, -27.654]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_93.geometry} material={nodes.cube_93.material} position={[-0.023, 9.139, 9.406]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_94.geometry} material={nodes.cube_94.material} position={[27.457, 0.009, -36.814]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_95.geometry} material={nodes.cube_95.material} position={[9.097, 0.009, 18.706]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_96.geometry} material={nodes.cube_96.material} position={[-0.026, 0.009, 18.706]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_97.geometry} material={nodes.cube_97.material} position={[-9.153, 0.009, 18.706]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_98.geometry} material={nodes.cube_98.material} position={[-9.153, 0.009, 9.406]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_99.geometry} material={nodes.cube_99.material} position={[27.457, -9.091, -36.814]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_100.geometry} material={nodes.cube_100.material} position={[9.099, -17.132, 30.74]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_101.geometry} material={nodes.cube_101.material} position={[-0.026, -9.121, 18.706]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_102.geometry} material={nodes.cube_102.material} position={[-9.151, 9.139, 36.816]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_103.geometry} material={nodes.cube_103.material} position={[-0.023, 0.009, 9.406]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_104.geometry} material={nodes.cube_104.material} position={[27.188, -18.256, -9.45]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_105.geometry} material={nodes.cube_105.material} position={[9.097, 9.139, 36.816]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_106.geometry} material={nodes.cube_106.material} position={[-0.026, 9.139, 36.816]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_107.geometry} material={nodes.cube_107.material} position={[-9.151, 9.139, 36.816]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_108.geometry} material={nodes.cube_108.material} position={[-0.023, -9.121, 9.406]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_115.geometry} material={nodes.cube_115.material} position={[27.457, -27.301, -36.814]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_116.geometry} material={nodes.cube_116.material} position={[9.14, -27.301, -36.814]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_117.geometry} material={nodes.cube_117.material} position={[-18.268, -27.301, -36.814]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_118.geometry} material={nodes.cube_118.material} position={[-27.393, -8.921, -36.814]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_120.geometry} material={nodes.cube_120.material} position={[-27.393, 0.199, -36.814]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_121.geometry} material={nodes.cube_121.material} position={[18.227, 27.366, -36.816]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_134.geometry} material={nodes.cube_134.material} position={[27.347, 27.366, -36.816]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_135.geometry} material={nodes.cube_135.material} position={[-0.023, 9.139, 0.276]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_136.geometry} material={nodes.cube_136.material} position={[-0.023, -9.121, 0.276]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_137.geometry} material={nodes.cube_137.material} position={[9.097, 0.009, 0.276]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_139.geometry} material={nodes.cube_139.material} position={[27.39, 18.283, -9.519]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_140.geometry} material={nodes.cube_140.material} position={[27.39, 9.153, -9.519]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_141.geometry} material={nodes.cube_141.material} position={[-0.023, 0.009, 0.276]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_142.geometry} material={nodes.cube_142.material} position={[-36.403, 0.218, -36.75]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_143.geometry} material={nodes.cube_143.material} position={[27.39, 0.023, -9.519]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_146.geometry} material={nodes.cube_146.material} position={[27.39, -9.107, -9.519]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_148.geometry} material={nodes.cube_148.material} position={[-0.038, -27.046, -9.536]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_149.geometry} material={nodes.cube_149.material} position={[-9.163, -27.046, -9.536]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_150.geometry} material={nodes.cube_150.material} position={[-18.293, -27.046, -9.536]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_151.geometry} material={nodes.cube_151.material} position={[9.097, 0.009, 9.406]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_152.geometry} material={nodes.cube_152.material} position={[-9.153, 0.009, 0.276]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_109.geometry} material={nodes.cube_109.material} position={[27.457, -18.151, -36.814]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_110.geometry} material={nodes.cube_110.material} position={[18.255, -27.301, -36.814]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_111.geometry} material={nodes.cube_111.material} position={[0.052, -27.301, -36.814]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_112.geometry} material={nodes.cube_112.material} position={[-9.084, -27.301, -36.814]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_113.geometry} material={nodes.cube_113.material} position={[-27.393, -27.301, -36.814]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_114.geometry} material={nodes.cube_114.material} position={[-27.393, -18.071, -36.814]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_119.geometry} material={nodes.cube_119.material} position={[-27.393, 9.339, -36.814]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_122.geometry} material={nodes.cube_122.material} position={[-27.393, 18.219, -36.814]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_123.geometry} material={nodes.cube_123.material} position={[-27.444, 18.236, -9.523]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_124.geometry} material={nodes.cube_124.material} position={[-27.444, 9.111, -9.523]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_125.geometry} material={nodes.cube_125.material} position={[-27.444, -0.019, -9.523]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_126.geometry} material={nodes.cube_126.material} position={[-27.444, -9.149, -9.523]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_127.geometry} material={nodes.cube_127.material} position={[-18.293, -27.409, -9.523]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_128.geometry} material={nodes.cube_128.material} position={[-27.444, -18.279, -9.523]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_129.geometry} material={nodes.cube_129.material} position={[27.347, 18.219, -36.814]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_130.geometry} material={nodes.cube_130.material} position={[18.237, 27.409, -9.364]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_131.geometry} material={nodes.cube_131.material} position={[36.4, 0.009, -18.582]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_132.geometry} material={nodes.cube_132.material} position={[9.392, -8.824, 27.616]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_133.geometry} material={nodes.cube_133.material} position={[18.334, 0.042, 27.615]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_138.geometry} material={nodes.cube_138.material} position={[18.237, 27.409, -9.36]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_144.geometry} material={nodes.cube_144.material} position={[10.591, -11.222, 30.091]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_145.geometry} material={nodes.cube_145.material} position={[18.389, -8.911, 27.616]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_147.geometry} material={nodes.cube_147.material} position={[18.227, -27.381, -9.45]} />
        </group>
        <group position={[-9.106, -13.795, 4.576]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh castShadow receiveShadow geometry={nodes.cube_32.geometry} material={nodes.cube_32.material} position={[27.303, -13.697, 27.596]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_33.geometry} material={nodes.cube_33.material} position={[9.049, -13.697, 27.596]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_34.geometry} material={nodes.cube_34.material} position={[27.303, 4.563, 27.596]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_35.geometry} material={nodes.cube_35.material} position={[18.174, 13.693, 27.596]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_36.geometry} material={nodes.cube_36.material} position={[9.049, 13.693, 27.596]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_39.geometry} material={nodes.cube_39.material} position={[-0.076, 13.693, 27.596]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_40.geometry} material={nodes.cube_40.material} position={[18.174, 4.563, 27.596]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_41.geometry} material={nodes.cube_41.material} position={[9.049, 4.563, 27.596]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_42.geometry} material={nodes.cube_42.material} position={[-0.079, 4.563, 27.596]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_43.geometry} material={nodes.cube_43.material} position={[-9.199, 4.563, 27.596]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_44.geometry} material={nodes.cube_44.material} position={[27.303, -4.567, 27.596]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_45.geometry} material={nodes.cube_45.material} position={[18.171, -4.567, 27.596]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_46.geometry} material={nodes.cube_46.material} position={[9.049, -4.567, 27.596]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_47.geometry} material={nodes.cube_47.material} position={[-0.079, -4.567, 27.596]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_48.geometry} material={nodes.cube_48.material} position={[-9.201, -4.567, 27.596]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_49.geometry} material={nodes.cube_49.material} position={[27.303, -13.697, 27.596]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_50.geometry} material={nodes.cube_50.material} position={[18.171, -13.697, 27.596]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_51.geometry} material={nodes.cube_51.material} position={[9.049, -13.697, 27.596]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_52.geometry} material={nodes.cube_52.material} position={[-0.079, -13.697, 27.596]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_53.geometry} material={nodes.cube_53.material} position={[-9.201, -13.697, 27.596]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_54.geometry} material={nodes.cube_54.material} position={[27.303, -22.832, 27.596]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_55.geometry} material={nodes.cube_55.material} position={[18.174, -22.832, 27.596]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_56.geometry} material={nodes.cube_56.material} position={[9.049, -22.832, 27.596]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_57.geometry} material={nodes.cube_57.material} position={[-0.076, -22.832, 27.596]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_58.geometry} material={nodes.cube_58.material} position={[-9.201, -22.832, 27.596]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_76.geometry} material={nodes.cube_76.material} position={[27.301, -13.697, 27.596]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_77.geometry} material={nodes.cube_77.material} position={[18.174, -13.697, 27.596]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_78.geometry} material={nodes.cube_78.material} position={[9.049, -13.697, 27.596]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_79.geometry} material={nodes.cube_79.material} position={[-0.076, -13.697, 27.596]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_80.geometry} material={nodes.cube_80.material} position={[-8.943, -4.633, 18.572]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_81.geometry} material={nodes.cube_81.material} position={[-9.201, -13.697, 27.596]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_37.geometry} material={nodes.cube_37.material} position={[-0.43, -13.727, 18.433]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_38.geometry} material={nodes.cube_38.material} position={[-9.199, 13.693, 27.596]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_59.geometry} material={nodes.cube_59.material} position={[-9.209, 22.833, -18.594]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_60.geometry} material={nodes.cube_60.material} position={[-9.209, 22.833, -18.594]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_61.geometry} material={nodes.cube_61.material} position={[-0.105, 22.833, -18.594]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_62.geometry} material={nodes.cube_62.material} position={[9.026, 22.833, -18.594]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_63.geometry} material={nodes.cube_63.material} position={[18.131, 22.833, -18.594]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_64.geometry} material={nodes.cube_64.material} position={[27.301, 13.693, 27.596]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_65.geometry} material={nodes.cube_65.material} position={[-0.079, 4.563, 27.596]} />
          <mesh castShadow receiveShadow geometry={nodes.eye_7.geometry} material={nodes.eye_7.material} position={[-0.079, 4.558, 27.596]} />
          <mesh castShadow receiveShadow geometry={nodes.eye_8.geometry} material={nodes.eye_8.material} position={[-0.079, -4.567, 27.596]} />
          <mesh castShadow receiveShadow geometry={nodes.eye_9.geometry} material={nodes.eye_9.material} position={[-0.079, -13.697, 27.596]} />
          <mesh castShadow receiveShadow geometry={nodes.eye_10.geometry} material={nodes.eye_10.material} position={[-0.079, 4.558, 27.596]} />
          <mesh castShadow receiveShadow geometry={nodes.eye_11.geometry} material={nodes.eye_11.material} position={[-0.079, -4.567, 27.596]} />
          <mesh castShadow receiveShadow geometry={nodes.eye_12.geometry} material={nodes.eye_12.material} position={[-0.079, -13.697, 27.596]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_72.geometry} material={nodes.cube_72.material} position={[-9.045, -13.676, 18.565]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_73.geometry} material={nodes.cube_73.material} position={[-27.303, -4.455, -27.596]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_74.geometry} material={nodes.cube_74.material} position={[-0.079, -22.827, 27.596]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_75.geometry} material={nodes.cube_75.material} position={[18.171, -13.697, 27.596]} />
        </group>
        <group position={[-0.055, -18.019, -4.509]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh castShadow receiveShadow geometry={nodes.cube_1.geometry} material={nodes.cube_1.material} position={[18.252, 22.763, 14.242]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_2.geometry} material={nodes.cube_2.material} position={[-0.002, -4.613, 14.242]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_3.geometry} material={nodes.cube_3.material} position={[18.252, 13.647, 14.242]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_7.geometry} material={nodes.cube_7.material} position={[9.123, 13.647, 14.242]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_8.geometry} material={nodes.cube_8.material} position={[-0.002, 13.647, 14.242]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_9.geometry} material={nodes.cube_9.material} position={[-9.13, 13.647, 14.242]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_10.geometry} material={nodes.cube_10.material} position={[-18.252, 13.647, 14.242]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_4.geometry} material={nodes.cube_4.material} position={[9.123, 22.777, 14.242]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_5.geometry} material={nodes.cube_5.material} position={[-0.002, 22.777, 14.242]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_6.geometry} material={nodes.cube_6.material} position={[-9.127, 22.777, 14.242]} />
          <mesh castShadow receiveShadow geometry={nodes.eye_6.geometry} material={nodes.eye_6.material} position={[-9.13, 4.517, 14.242]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_12.geometry} material={nodes.cube_12.material} position={[9.123, 4.517, 14.242]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_13.geometry} material={nodes.cube_13.material} position={[-0.002, 4.517, 14.242]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_14.geometry} material={nodes.cube_14.material} position={[-9.127, 4.517, 14.242]} />
          <mesh castShadow receiveShadow geometry={nodes.eye_1.geometry} material={nodes.eye_1.material} position={[-9.13, 4.517, 22.944]} />
          <mesh castShadow receiveShadow geometry={nodes.eye_5.geometry} material={nodes.eye_5.material} position={[-9.13, -4.613, 20.888]} />
          <mesh castShadow receiveShadow geometry={nodes.eye_4.geometry} material={nodes.eye_4.material} position={[-9.13, -4.613, 14.242]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_18.geometry} material={nodes.cube_18.material} position={[-0.002, -4.613, 14.242]} />
          <mesh castShadow receiveShadow geometry={nodes.eye_3.geometry} material={nodes.eye_3.material} position={[9.12, -4.613, 14.242]} />
          <mesh castShadow receiveShadow geometry={nodes.eye_2.geometry} material={nodes.eye_2.material} position={[9.12, -4.613, 22.944]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_21.geometry} material={nodes.cube_21.material} position={[18.252, -13.635, 14.242]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_22.geometry} material={nodes.cube_22.material} position={[9.123, -13.748, 14.242]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_23.geometry} material={nodes.cube_23.material} position={[-0.002, -13.748, 14.242]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_24.geometry} material={nodes.cube_24.material} position={[-9.127, -13.748, 14.242]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_25.geometry} material={nodes.cube_25.material} position={[-18.252, -13.748, 14.242]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_26.geometry} material={nodes.cube_26.material} position={[18.25, -22.813, -22.944]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_27.geometry} material={nodes.cube_27.material} position={[9.123, -22.813, -22.944]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_28.geometry} material={nodes.cube_28.material} position={[-0.002, -4.613, 14.242]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_29.geometry} material={nodes.cube_29.material} position={[-9.127, -4.613, 14.242]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_30.geometry} material={nodes.cube_30.material} position={[-18.252, -4.613, 14.242]} />
          <mesh castShadow receiveShadow geometry={nodes.cube_31.geometry} material={nodes.cube_31.material} position={[-18.252, 22.813, 14.242]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/assets/model/cub.gltf')
